# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "contacts"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/contacts"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json", "js/**.js.map", "js/**.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/favicon-mask.svg", "img/favicon-touch.png", "img/favicon-touch.svg", "img/favicon.ico", "img/favicon.png", "img/favicon.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC, 2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".tx/config", "package-lock.json", "package.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 ownCloud, Inc., 2016-2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["composer.json", "composer.lock", "img/no-calendar.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "tsconfig.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ".github/CODEOWNERS"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "renovate.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/address-book.svg", "img/circles.svg", "img/clone.svg", "img/eye.svg", "img/language.svg", "img/phone.svg", "img/qrcode.svg", "img/recent-actors.svg", "img/social.svg", "img/sync.svg", "img/up.svg", "img/contacts.svg", "img/app.svg", "img/group.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "img/facebook.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Meta"
SPDX-License-Identifier = "LicenseRef-FacebookTrademarks"

[[annotations]]
path = "img/instagram.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Meta"
SPDX-License-Identifier = "LicenseRef-InstagramTrademarks"

[[annotations]]
path = "img/diaspora.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Diaspora"
SPDX-License-Identifier = "LicenseRef-DiasporaTrademarks"

[[annotations]]
path = "img/mastodon.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Mastodon gGmbH"
SPDX-License-Identifier = "LicenseRef-MastodonTrademarks"

[[annotations]]
path = "img/tumblr.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Tumblr, Inc."
SPDX-License-Identifier = "LicenseRef-TumblrTrademarks"

[[annotations]]
path = "img/xing.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "fontawesome.com <https://fontawesome.com/icons/xing?style=brands>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "img/gravatar.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "svgrepo.com <https://www.svgrepo.com/page/licensing>"
SPDX-License-Identifier = "CC0-1.0"
